// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var ChildProcess = 0;

var Events = 0;

var Net = 0;

var Stream = 0;

exports.ChildProcess = ChildProcess;
exports.Events = Events;
exports.Net = Net;
exports.Stream = Stream;
/* No side effect */
