// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Writable = { };

var Readable = { };

var Duplex = { };

exports.Writable = Writable;
exports.Readable = Readable;
exports.Duplex = Duplex;
/* No side effect */
